### ISSUE TITLE
make a codesandbox demo?

### ISSUE THREAD

**Issue by sw-yx** [arackaf/micro-graphql-react#12]
hey adam! feel free to close but just thinking that it would be a bit easier to take micro-graphql-react out for a spin in a codesandbox. think thats the trend for people evaluating libraries. cheers though this looks very promising

**Comment by sw-yx** [comment]
got this one from pomber https://github.com/APIs-guru/graphql-apis

**Comment by arackaf** [comment]
@sw-yx - thanks a ton - I hope you didn't spend a lot of time getting those graphql endpoints, and if you did, that they'll be of some use to you outside of here.

I'm gonna try and get a public facing graphql endpoint up and running from my existing booklist db. Here goes nothing ...

**Comment by sw-yx** [comment]
yup i was doing this in part for myself too since i need to do demos for my babel plugin haha

**Comment by sw-yx** [comment]
i had a convo with @gsans yesterday about this pain point, and he had a few other demo api suggestions

**Comment by arackaf** [comment]
Oh whoops - I should have updated this case - the CodeSandbox demo is up, and linked from the README 

https://codesandbox.io/s/l2z74x2687

**Comment by arackaf** [comment]
Closing this - like I said, CodeSandbox link is on the main readmd
