### ISSUE TITLE
get results of a mutation?

### ISSUE THREAD

**Issue by bzbetty** [arackaf/micro-graphql-react#15]
running a mutation using the useMutation hook but I can't see any way of getting the results.

Wanted to get the item after a CREATE and redirect to view it, am I missing something?

**Comment by bzbetty** [comment]
ah i see runMutation is a promise, I thought it'd come back via the hook.

**Comment by arackaf** [comment]
useMutation gives you a function that you can call later (ie in an event handler) which returns a promise. This is, iirc, also how Apollo works. Urql does indeed give you the execute function *and* result from the hook, but this would preclude you (I think) from re-using the mutation function

**Comment by bzbetty** [comment]
All good, I can wrap it in my own hook to make it behave how I like where needed.  It just makes using redirects in react-router-dom a bit nicer since they're jsx elements that need to be rendered (for some unknown reason)

**Comment by arackaf** [comment]
Ah - indeed! Good thinking!
