### ISSUE TITLE
Access to response headers / status code?

### ISSUE THREAD

**Issue by bzbetty** [arackaf/micro-graphql-react#17]
i'd like to add in some extra http headers for 401 responses letting them know where to get a token, but I notice there's no way to get this information back out in your library.  Wondering if it makes sense to add the raw response to the state returned by useQuery, or maybe access to the requests promise?

**Comment by arackaf** [comment]
Adding the raw response to the query state sounds great.  I'm a bit tied up at the moment, but if you wanna PR that, I'd be happy to accept.  You'll want to update things here:

https://github.com/arackaf/micro-graphql-react/blob/master/src/queryManager.js#L107-L111

and that should automatically update both the useQuery hook, and also the GraphQL render props component. Let me know if you need more help / info

**Comment by arackaf** [comment]
Whoops - you'll also want to update this, for cached queries 

https://github.com/arackaf/micro-graphql-react/blob/master/src/queryManager.js#L87

**Comment by arackaf** [comment]
Sorry - one last update. *Might* not make sense to put the entire response object into the query state - there’s weird restrictions on how many times the response can be streamed and such, isn’t there? 

Might be better to pluck the headers, etc from the response when it first comes back, and add *that* to the query state.

**Comment by bzbetty** [comment]
you're right, probably don't want to give direct access to the body stream that could get rather odd.

I was thinking through my potential use cases and now I'm actually wondering if instead of returning headers / response it'd be better to have common events on the client class, generally this idea was for cross cutting concerns like 401's and 302's that would likely be handled the same throughout the code.

so something like:

```
const client = new Client({
  endpoint: "/graphql",
  fetchOptions: { credentials: "include" },
  fetchEvents: {
      beforeFetch: () => {},
      afterFetch: () => {},
      catch: () => {},
  }
});

setDefaultClient(client);
```

or maybe some kind of extension to the query events?

```
buildQuery(
          BOOKS_QUERY,
          { page: props.page },
          {
            onFetch: {
              when: "401",
              run: () => { }
            }
          }
        )
```

**Comment by arackaf** [comment]
Hmmm - trying to force in AOP seems like it'd be tricky to get right.  I'm really thinking adding a `__responseMetadata` (or whatever) with response codes, etc., would be the best work:reward proposition.

Thoughts?

**Comment by bzbetty** [comment]
I'll have a play with a few things to see what seems useful.

Which is your latest branch? master doesn't seem to line up with what's in npm

**Comment by arackaf** [comment]
Whoops - master is up to date now - thanks!
