### ISSUE TITLE
Mutation subscriptions being removed early by useLayoutEffect

### ISSUE THREAD

**Issue by bzbetty** [arackaf/micro-graphql-react#18]
So i've noticed that some of my mutation subscriptions are never fired, thus leaving me with a stale cache.

It appears that the query manager is getting disposed by the useQuery hook and thus removing the mutationSubscription, but leaving the cache untouched.

I can get around this issue by querying data that might need to be invalidated on every page to ensure the subscription is readded, but that doesn't feel right.  

Is there any way to keep the queryManager around?

```
function useQuery() {
 ...
  useLayoutEffect(() => () => queryManager.current && queryManager.current.dispose(), []);
}
```

**Comment by arackaf** [comment]
Hi!  If you're setting up cache update code in your `useQuery` hook, then it'll be torn down and removed when the hook unmounts.  If you want to just globally subscribe to mutations, and update the cache as needed, check out this section:

https://github.com/arackaf/micro-graphql-react#use-case-4-globally-modify-the-cache-as-needed 

Just don't forget to call `graphqlClient.forceUpdate(queryName)`

**Comment by bzbetty** [comment]
hmm that might work! thanks, will give it a go.

**Comment by bzbetty** [comment]
Using global modifying works

**Comment by arackaf** [comment]
Woot woot - glad to hear!
