### ISSUE TITLE
Array in sending grapql query  variables cause error 400 

### ISSUE THREAD

**Issue by McMardock** [arackaf/micro-graphql-react#21]
I didn't manage to send array in grapql query variable, because of each request cause HTTP error 400

example variable which  were tried to send: 
{"problemRequest":{"problem":{"problem_id":{"id":1000},"packages_list":[{"id":1046242451},{"id":1046192872},{"id":1046255145}]}}}

my workaround was to modified getGraphqlQuery function
return `${this.endpoint}?query=${encodeURIComponent(query)}${typeof variables === "object" ? `&variables=${**encodeURIComponent**(JSON.stringify(variables))}` : ""}`;

**Comment by arackaf** [comment]
Ah - I think I see. Can you clarify what sorts of characters in the variables object cause this bug, so I can try to repro? Is it an array?

Also, what browser?

**Comment by arackaf** [comment]
Fixed and published in 0.3.3

Thanks a ton for the bug report!
