### ISSUE TITLE
Query component

### ISSUE THREAD

**Issue by fabiancook** [arackaf/micro-graphql-react#7]
Would be great to have a "children as a function" component (There must be a name for this now?) where you pass your query and variables to it, which then invokes the child...

```
<Query query={query} variables={{a: 1}}>
{({loading, loaded, data, error}) => <div>Do something</div>}
</Query>
```

**Comment by arackaf** [comment]
There is indeed a name for it: render props :)

I already have a case for it here: https://github.com/arackaf/micro-graphql-react/issues/3
